import type { AssetRef } from '../model/scene';
import { guessFit } from './catalog';

/**
 * The full Poly by Google library (2,000+ CC-BY models) from poly.pizza.
 * The index is generated by scripts/build-poly-catalog.mjs into public/catalog/poly-google.json;
 * models and thumbnails are fetched on demand from Poly Pizza's CDN (CORS-enabled, no API key needed).
 */

export interface PolyEntry {
  id: string;
  file: string;
  title: string;
  licence: string;
}

interface CatalogFile {
  format: 'previzxr.catalog';
  creator: string;
  licences: string[];
  models: Array<[id: string, file: string, title: string, licence: number]>;
}

const CDN = 'https://static.poly.pizza';
export const POLY_CREATOR = 'Poly by Google';

export const polyModelUrl = (file: string) => `${CDN}/${file}.glb`;
export const polyThumbUrl = (file: string) => `${CDN}/${file}.webp`;
export const polyPageUrl = (id: string) => `https://poly.pizza/m/${id}`;

let loading: Promise<PolyEntry[]> | null = null;

/** Loads the index once (about 90 kB gzipped). */
export function loadPolyLibrary(): Promise<PolyEntry[]> {
  loading ??= fetch(`${import.meta.env.BASE_URL}catalog/poly-google.json`)
    .then((r) => {
      if (!r.ok) throw new Error(`Could not load the model library (${r.status})`);
      return r.json() as Promise<CatalogFile>;
    })
    .then((c) => c.models.map(([id, file, title, lic]) => ({ id, file, title, licence: c.licences[lic] })))
    .catch((err) => {
      loading = null;
      throw err;
    });
  return loading;
}

/** Case-insensitive search: every word must appear in the title; titles starting with the query rank first. */
export function searchPoly(entries: PolyEntry[], query: string, limit = 60): PolyEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return entries.slice(0, limit);
  const words = q.split(/\s+/);
  const hits = entries.filter((e) => {
    const t = e.title.toLowerCase();
    return words.every((w) => t.includes(w));
  });
  hits.sort((a, b) => rank(a.title, q) - rank(b.title, q) || a.title.localeCompare(b.title));
  return hits.slice(0, limit);
}

function rank(title: string, q: string): number {
  const t = title.toLowerCase();
  if (t === q) return 0;
  if (t.startsWith(q)) return 1;
  return 2;
}

export function polyAssetRef(e: PolyEntry): Extract<AssetRef, { source: 'poly' }> {
  return { source: 'poly', id: e.id, file: e.file, title: e.title, creator: POLY_CREATOR, licence: e.licence, fit: guessFit(e.title) };
}
