import type { AssetRef, Fit } from '../model/scene';
import { guessFit, type CatalogItem } from './catalog';

/**
 * Creator libraries from poly.pizza: Poly by Google (2,000+ CC-BY models) and Quaternius (1,400+, mostly CC0,
 * including animated characters and animals). Each index is generated by scripts/build-poly-catalog.mjs into
 * public/catalog/; models and thumbnails are fetched on demand from Poly Pizza's CDN (CORS-enabled, no API key needed).
 */

export type PolyLibraryId = 'google' | 'quaternius';

export interface PolyLibrary {
  id: PolyLibraryId;
  /** Creator name on poly.pizza (also the credit author). */
  creator: string;
  index: string;
  /** Licence summary for the UI. */
  licence: string;
  /** Suggested searches for the VR menu, which has no keyboard. */
  presets: string[];
}

export const POLY_LIBRARIES: readonly PolyLibrary[] = [
  {
    id: 'google',
    creator: 'Poly by Google',
    index: 'poly-google.json',
    licence: 'CC-BY 3.0',
    presets: ['chair', 'table', 'couch', 'car', 'truck', 'tree', 'plant', 'lamp', 'house', 'dog'],
  },
  {
    id: 'quaternius',
    creator: 'Quaternius',
    index: 'quaternius.json',
    licence: 'mostly CC0',
    presets: ['animated', 'character', 'zombie', 'robot', 'horse', 'fish', 'tree', 'house', 'car', 'gun'],
  },
];

export function polyLibrary(id: PolyLibraryId): PolyLibrary {
  return POLY_LIBRARIES.find((l) => l.id === id) ?? POLY_LIBRARIES[0];
}

export interface PolyEntry {
  id: string;
  file: string;
  title: string;
  creator: string;
  licence: string;
  /** Animation clips in the model (animated models only); these spawn as actors. */
  clips?: string[];
  /** Skinned humanoid: sized as a person. */
  humanoid?: boolean;
}

interface CatalogFile {
  format: 'previzxr.catalog';
  creator: string;
  licences: string[];
  models: Array<[id: string, file: string, title: string, licence: number, clips?: string[], humanoid?: number]>;
}

const CDN = 'https://static.poly.pizza';
/** Height of a person-shaped library character, in metres. */
const HUMANOID_HEIGHT = 1.75;

export const polyModelUrl = (file: string) => `${CDN}/${file}.glb`;
export const polyThumbUrl = (file: string) => `${CDN}/${file}.webp`;
export const polyPageUrl = (id: string) => `https://poly.pizza/m/${id}`;
export const polyCreatorUrl = (lib: PolyLibrary) => `https://poly.pizza/u/${encodeURIComponent(lib.creator)}`;

const loading = new Map<PolyLibraryId, Promise<PolyEntry[]>>();

/** Loads a library's index once (60–90 kB gzipped). */
export function loadPolyLibrary(id: PolyLibraryId = 'google'): Promise<PolyEntry[]> {
  let pending = loading.get(id);
  if (!pending) {
    pending = fetch(`${import.meta.env.BASE_URL}catalog/${polyLibrary(id).index}`)
      .then((r) => {
        if (!r.ok) throw new Error(`Could not load the model library (${r.status})`);
        return r.json() as Promise<CatalogFile>;
      })
      .then(parseCatalog)
      .catch((err) => {
        loading.delete(id);
        throw err;
      });
    loading.set(id, pending);
  }
  return pending;
}

export function parseCatalog(c: CatalogFile): PolyEntry[] {
  return c.models.map(([id, file, title, lic, clips, humanoid]) => {
    const e: PolyEntry = { id, file, title, creator: c.creator, licence: c.licences[lic] };
    if (clips?.length) e.clips = clips;
    if (humanoid) e.humanoid = true;
    return e;
  });
}

/** Case-insensitive search: every word must appear in the title; titles starting with the query rank first. */
export function searchPoly(entries: PolyEntry[], query: string, limit = 60): PolyEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return entries.slice(0, limit);
  const words = q.split(/\s+/);
  const hits = entries.filter((e) => {
    const t = e.title.toLowerCase();
    return words.every((w) => t.includes(w));
  });
  hits.sort((a, b) => rank(a.title, q) - rank(b.title, q) || a.title.localeCompare(b.title));
  return hits.slice(0, limit);
}

function rank(title: string, q: string): number {
  const t = title.toLowerCase();
  if (t === q) return 0;
  if (t.startsWith(q)) return 1;
  return 2;
}

export function polyAssetRef(e: PolyEntry): Extract<AssetRef, { source: 'poly' }> {
  const fit: Fit = e.humanoid ? { axis: 'height', size: HUMANOID_HEIGHT } : guessFit(e.title);
  const ref: Extract<AssetRef, { source: 'poly' }> = { source: 'poly', id: e.id, file: e.file, title: e.title, creator: e.creator, licence: e.licence, fit };
  if (e.clips) ref.clips = [...e.clips];
  return ref;
}

/** What the Add panel and VR menu spawn: animated models become actors that play their own clips. */
export function polySpawnable(e: PolyEntry): Pick<CatalogItem, 'title' | 'kind' | 'asset'> {
  return { title: e.title, kind: e.clips ? 'actor' : 'prop', asset: polyAssetRef(e) };
}
